name: node_program_editor
description: "A drag and drop UI to create json block sequence, inspired by LabView and Simulink"
version: 1.0.1
homepage: https://github.com/avagst3/node_program_editor#

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  diagram_editor: ^0.2.3
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  auto_size_text: ^3.0.0
  file_picker: ^10.1.9
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
