name: node_program_editor
description: "A drag and drop base to create node graph"
version: 2.1.0
homepage: https://github.com/avagst3/node_program_editor#

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
